# Generated by Django 5.2.6 on 2025-09-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_category_event_eventpackage_promotion_analytics_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workeravailability',
            unique_together={('worker', 'date')},
        ),
        migrations.AddField(
            model_name='workeravailability',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='workeravailability',
            name='available',
        ),
        migrations.RemoveField(
            model_name='workeravailability',
            name='slot',
        ),
    ]
