# Generated by Django 5.2.6 on 2025-09-22 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_workeravailability_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerportfolio',
            name='media_file',
        ),
        migrations.RemoveField(
            model_name='workerportfolio',
            name='media_type',
        ),
        migrations.AddField(
            model_name='workerportfolio',
            name='video',
            field=models.FileField(blank=True, help_text='Optional video under 3 minutes', null=True, upload_to='portfolio/videos/'),
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/images/')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='jobs.workerportfolio')),
            ],
        ),
    ]
