# Generated by Django 5.2.6 on 2025-09-22 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_workerportfolio_media_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerportfolio',
            name='video',
        ),
        migrations.AlterField(
            model_name='workerportfolio',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='PortfolioMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='portfolio_media/')),
                ('is_video', models.BooleanField(default=False)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='jobs.workerportfolio')),
            ],
        ),
        migrations.DeleteModel(
            name='PortfolioImage',
        ),
    ]
