# Generated by Django 5.2.6 on 2025-09-22 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_reviewmedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='media_file',
        ),
    ]
