# Generated by Django 5.2.6 on 2025-09-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_remove_review_media_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='workers', to='jobs.category'),
        ),
    ]
