# Generated by Django 5.2.6 on 2025-10-12 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_auditlog_payment_auditlog_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='advance_percentage',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=5),
        ),
    ]
