# Generated by Django 5.2.6 on 2025-10-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_sitesettings_advance_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('advance', 'Advance'), ('balance', 'Balance')], default='advance', max_length=10),
        ),
    ]
