# Generated by Django 5.2.6 on 2025-10-18 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_payment_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerVerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('id_document', models.FileField(upload_to='verifications/id_documents/')),
                ('selfie', models.ImageField(upload_to='verifications/selfies/')),
                ('certificates', models.FileField(blank=True, null=True, upload_to='verifications/certificates/')),
                ('portfolio', models.FileField(blank=True, null=True, upload_to='verifications/portfolio/')),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('verification_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
