# Generated by Django 5.2.6 on 2025-10-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_workerverificationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerverificationrequest',
            name='verified_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
