# Generated by Django 5.2.6 on 2025-10-19 03:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_workerverificationrequest_verified_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='bookingimage',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='bookingimage',
            name='file',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='bookings/'),
            preserve_default=False,
        ),
    ]
