# Generated by Django 5.2.6 on 2025-10-20 11:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0023_supportticket_ticketreply'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('performance', 'Performance Issue'), ('payment', 'Payment Issue'), ('behavior', 'Behavior Issue'), ('no_show', 'No Show'), ('customer_complaint', 'Customer Complaint'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField(help_text='Detailed description of the issue')),
                ('evidence', models.FileField(blank=True, help_text='Optional: Image, video, or document evidence', null=True, upload_to='worker_reports/evidence/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin review', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_reports', to='jobs.booking')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_worker_reports', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='jobs.workerprofile')),
            ],
            options={
                'verbose_name': 'Worker Report',
                'verbose_name_plural': 'Worker Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
